--------------------------------------------------------
--  File created - Friday-July-04-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."USERS" 
   (	"USERID" VARCHAR2(10), 
	"USERNAME" VARCHAR2(50), 
	"EMAIL" VARCHAR2(30), 
	"PASSWORD" VARCHAR2(50), 
	"ROLE" VARCHAR2(10), 
	 PRIMARY KEY ("USERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Table TASK
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."TASK" 
   (	"TASKID" VARCHAR2(8), 
	"TASKDESCRIPTION" VARCHAR2(50), 
	"ASSIGNEDTOSTAFF" VARCHAR2(30), 
	"STATUS" VARCHAR2(15), 
	 PRIMARY KEY ("TASKID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Table SUPPLIER
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."SUPPLIER" 
   (	"SUPPLIERID" VARCHAR2(10), 
	"SUPPLIERNAME" VARCHAR2(20), 
	"CONTACTNO" VARCHAR2(11), 
	 PRIMARY KEY ("SUPPLIERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Table ROOM
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."ROOM" 
   (	"ROOMID" VARCHAR2(10), 
	"ROOMNUMBER" VARCHAR2(10), 
	"ROOMPRICE" VARCHAR2(10), 
	"ROOMSTATUS" VARCHAR2(10), 
	"ROOMCATEGORY" VARCHAR2(30), 
	 PRIMARY KEY ("ROOMID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Table REGISTER
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."REGISTER" 
   (	"USERNAME" VARCHAR2(20) NOT NULL ENABLE, 
	"EMAIL" VARCHAR2(30) NOT NULL ENABLE, 
	"PASS" VARCHAR2(15) NOT NULL ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Table PAYROLL
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."PAYROLL" 
   (	"PAYROLL_ID" VARCHAR2(15), 
	"STAFF_ID" VARCHAR2(8) NOT NULL ENABLE, 
	"STAFF_NAME" VARCHAR2(50) NOT NULL ENABLE, 
	"DP" NUMBER(3,0) NOT NULL ENABLE, 
	"PAY_MONTH" VARCHAR2(20) NOT NULL ENABLE, 
	"AMOUNT_P" NUMBER(10,2) NOT NULL ENABLE, 
	"P_STATUS" VARCHAR2(10) NOT NULL ENABLE, 
	 CHECK (p_status IN ('Paid', 'Pending')) ENABLE, 
	 PRIMARY KEY ("PAYROLL_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Table ATTENDANCE
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."ATTENDANCE" 
   (	"STAFFID" VARCHAR2(8), 
	"ATT_DATE" DATE, 
	"STATUS" CHAR(8)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Table BOOKING
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."BOOKING" 
   (	"BOOKINGID" VARCHAR2(10), 
	"CHECKINDATE" DATE, 
	"CHECKOUTDATE" DATE, 
	"BOOKINGDATE" DATE, 
	"ROOMCATEGORY" VARCHAR2(10), 
	"GUESTNAME" VARCHAR2(15), 
	"ROOMID" VARCHAR2(10), 
	"USERNAME" VARCHAR2(50), 
	 PRIMARY KEY ("BOOKINGID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Table INVENTORY
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."INVENTORY" 
   (	"ITEMID" VARCHAR2(10), 
	"ITEMNAME" VARCHAR2(15), 
	"ITEMQUANTITY" NUMBER(3,0), 
	"STATUS" VARCHAR2(15)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Table FEEDBACK
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."FEEDBACK" 
   (	"FEEDBACKID" VARCHAR2(15), 
	"FEEDBACKTYPE" VARCHAR2(13), 
	"DESCRIPTION" VARCHAR2(250), 
	"STARS" NUMBER(5,0), 
	"USERID" VARCHAR2(10), 
	"USERNAME" VARCHAR2(50), 
	 PRIMARY KEY ("FEEDBACKID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 FOREIGN KEY ("USERID")
	  REFERENCES "SYSTEM"."USERS" ("USERID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
REM INSERTING into SYSTEM.USERS
SET DEFINE OFF;
Insert into SYSTEM.USERS (USERID,USERNAME,EMAIL,PASSWORD,ROLE) values ('GID001','eman_aijaz','eman@gmail.com','12345678','guest');
Insert into SYSTEM.USERS (USERID,USERNAME,EMAIL,PASSWORD,ROLE) values ('GID002','hafsa_zakir','hafsa@gmail.com','98765432','guest');
Insert into SYSTEM.USERS (USERID,USERNAME,EMAIL,PASSWORD,ROLE) values ('GID003','hamza_ahmed','hamza@gmail.com','emanaijaz','guest');
Insert into SYSTEM.USERS (USERID,USERNAME,EMAIL,PASSWORD,ROLE) values ('SID001','hiba_waseem','hiba@gmail.com','12345678','staff');
Insert into SYSTEM.USERS (USERID,USERNAME,EMAIL,PASSWORD,ROLE) values ('AID001','musa_ahmed','musa@gmail.com','987654321','admin');
Insert into SYSTEM.USERS (USERID,USERNAME,EMAIL,PASSWORD,ROLE) values ('AID002','hkhkhk','testing@gmail.com','12345678','admin');
REM INSERTING into SYSTEM.TASK
SET DEFINE OFF;
Insert into SYSTEM.TASK (TASKID,TASKDESCRIPTION,ASSIGNEDTOSTAFF,STATUS) values ('TID001','Clean Room 204','SID001','Pending');
Insert into SYSTEM.TASK (TASKID,TASKDESCRIPTION,ASSIGNEDTOSTAFF,STATUS) values ('TID002','Refill Mini Bar in Room 305','SID002','Completed');
Insert into SYSTEM.TASK (TASKID,TASKDESCRIPTION,ASSIGNEDTOSTAFF,STATUS) values ('TID003','Check Laundry for Room 110','SID001','In Progress');
Insert into SYSTEM.TASK (TASKID,TASKDESCRIPTION,ASSIGNEDTOSTAFF,STATUS) values ('TID004','Inspect HVAC in Room 410','SID003','Pending');
Insert into SYSTEM.TASK (TASKID,TASKDESCRIPTION,ASSIGNEDTOSTAFF,STATUS) values ('TID005','Deliver Towels to Room 208','SID004','Completed');
Insert into SYSTEM.TASK (TASKID,TASKDESCRIPTION,ASSIGNEDTOSTAFF,STATUS) values ('TID006','Prepare Banquet Hall','SID002','In Progress');
Insert into SYSTEM.TASK (TASKID,TASKDESCRIPTION,ASSIGNEDTOSTAFF,STATUS) values ('TID007','Check Kitchen Inventory','SID005','Pending');
Insert into SYSTEM.TASK (TASKID,TASKDESCRIPTION,ASSIGNEDTOSTAFF,STATUS) values ('TID008','Polish Lobby Floors','SID003','Completed');
Insert into SYSTEM.TASK (TASKID,TASKDESCRIPTION,ASSIGNEDTOSTAFF,STATUS) values ('TID009','Water Indoor Plants','SID001','Pending');
Insert into SYSTEM.TASK (TASKID,TASKDESCRIPTION,ASSIGNEDTOSTAFF,STATUS) values ('TID010','Setup Conference Room A','SID002','Completed');
REM INSERTING into SYSTEM.SUPPLIER
SET DEFINE OFF;
Insert into SYSTEM.SUPPLIER (SUPPLIERID,SUPPLIERNAME,CONTACTNO) values ('SI001','FreshLine Supply','98765432101');
Insert into SYSTEM.SUPPLIER (SUPPLIERID,SUPPLIERNAME,CONTACTNO) values ('SI002','Elite Hospitality','91234567890');
Insert into SYSTEM.SUPPLIER (SUPPLIERID,SUPPLIERNAME,CONTACTNO) values ('SI003','PrimePro Logistics','90123456789');
REM INSERTING into SYSTEM.ROOM
SET DEFINE OFF;
Insert into SYSTEM.ROOM (ROOMID,ROOMNUMBER,ROOMPRICE,ROOMSTATUS,ROOMCATEGORY) values ('RM001','1','1500','Available','Single');
Insert into SYSTEM.ROOM (ROOMID,ROOMNUMBER,ROOMPRICE,ROOMSTATUS,ROOMCATEGORY) values ('RM002','2','5000','Available','Deluxe');
Insert into SYSTEM.ROOM (ROOMID,ROOMNUMBER,ROOMPRICE,ROOMSTATUS,ROOMCATEGORY) values ('RM003','3','1500','Available','Single');
Insert into SYSTEM.ROOM (ROOMID,ROOMNUMBER,ROOMPRICE,ROOMSTATUS,ROOMCATEGORY) values ('RM004','4','8000','Available','Suite');
Insert into SYSTEM.ROOM (ROOMID,ROOMNUMBER,ROOMPRICE,ROOMSTATUS,ROOMCATEGORY) values ('RM005','5','8000','Available','Suite');
Insert into SYSTEM.ROOM (ROOMID,ROOMNUMBER,ROOMPRICE,ROOMSTATUS,ROOMCATEGORY) values ('RM006','6','8000','Available','Suite');
Insert into SYSTEM.ROOM (ROOMID,ROOMNUMBER,ROOMPRICE,ROOMSTATUS,ROOMCATEGORY) values ('RM007','7','8000','occupied','double');
REM INSERTING into SYSTEM.REGISTER
SET DEFINE OFF;
Insert into SYSTEM.REGISTER (USERNAME,EMAIL,PASS) values ('eman1','eman@gmail.com','1234');
Insert into SYSTEM.REGISTER (USERNAME,EMAIL,PASS) values ('eman1','eman@gmail.com','123');
Insert into SYSTEM.REGISTER (USERNAME,EMAIL,PASS) values ('hello','testing@gmail.com','2829');
Insert into SYSTEM.REGISTER (USERNAME,EMAIL,PASS) values ('efssfdf','eman.aijaz09@gmail.com','ksdawkeaw');
REM INSERTING into SYSTEM.PAYROLL
SET DEFINE OFF;
Insert into SYSTEM.PAYROLL (PAYROLL_ID,STAFF_ID,STAFF_NAME,DP,PAY_MONTH,AMOUNT_P,P_STATUS) values ('P001','SID001','Hiba Waseem',24,'April 2025',8640,'Pending');
Insert into SYSTEM.PAYROLL (PAYROLL_ID,STAFF_ID,STAFF_NAME,DP,PAY_MONTH,AMOUNT_P,P_STATUS) values ('P002','SID001','Hiba Waseem',23,'March 2025',8280,'Paid');
REM INSERTING into SYSTEM.ATTENDANCE
SET DEFINE OFF;
Insert into SYSTEM.ATTENDANCE (STAFFID,ATT_DATE,STATUS) values ('SID001',to_date('01-APR-25','DD-MON-RR'),'P       ');
Insert into SYSTEM.ATTENDANCE (STAFFID,ATT_DATE,STATUS) values ('SID001',to_date('02-APR-25','DD-MON-RR'),'P       ');
Insert into SYSTEM.ATTENDANCE (STAFFID,ATT_DATE,STATUS) values ('SID001',to_date('03-APR-25','DD-MON-RR'),'P       ');
Insert into SYSTEM.ATTENDANCE (STAFFID,ATT_DATE,STATUS) values ('SID001',to_date('04-APR-25','DD-MON-RR'),'P       ');
Insert into SYSTEM.ATTENDANCE (STAFFID,ATT_DATE,STATUS) values ('SID001',to_date('05-APR-25','DD-MON-RR'),'P       ');
Insert into SYSTEM.ATTENDANCE (STAFFID,ATT_DATE,STATUS) values ('SID001',to_date('06-APR-25','DD-MON-RR'),'A       ');
Insert into SYSTEM.ATTENDANCE (STAFFID,ATT_DATE,STATUS) values ('SID001',to_date('07-APR-25','DD-MON-RR'),'P       ');
Insert into SYSTEM.ATTENDANCE (STAFFID,ATT_DATE,STATUS) values ('SID001',to_date('08-APR-25','DD-MON-RR'),'P       ');
Insert into SYSTEM.ATTENDANCE (STAFFID,ATT_DATE,STATUS) values ('SID001',to_date('09-APR-25','DD-MON-RR'),'P       ');
Insert into SYSTEM.ATTENDANCE (STAFFID,ATT_DATE,STATUS) values ('SID001',to_date('10-APR-25','DD-MON-RR'),'P       ');
Insert into SYSTEM.ATTENDANCE (STAFFID,ATT_DATE,STATUS) values ('SID001',to_date('11-APR-25','DD-MON-RR'),'A       ');
Insert into SYSTEM.ATTENDANCE (STAFFID,ATT_DATE,STATUS) values ('SID001',to_date('12-APR-25','DD-MON-RR'),'A       ');
Insert into SYSTEM.ATTENDANCE (STAFFID,ATT_DATE,STATUS) values ('SID001',to_date('13-APR-25','DD-MON-RR'),'P       ');
Insert into SYSTEM.ATTENDANCE (STAFFID,ATT_DATE,STATUS) values ('SID001',to_date('14-APR-25','DD-MON-RR'),'P       ');
Insert into SYSTEM.ATTENDANCE (STAFFID,ATT_DATE,STATUS) values ('SID001',to_date('15-APR-25','DD-MON-RR'),'P       ');
Insert into SYSTEM.ATTENDANCE (STAFFID,ATT_DATE,STATUS) values ('SID001',to_date('16-APR-25','DD-MON-RR'),'P       ');
Insert into SYSTEM.ATTENDANCE (STAFFID,ATT_DATE,STATUS) values ('SID001',to_date('17-APR-25','DD-MON-RR'),'A       ');
Insert into SYSTEM.ATTENDANCE (STAFFID,ATT_DATE,STATUS) values ('SID001',to_date('18-APR-25','DD-MON-RR'),'A       ');
Insert into SYSTEM.ATTENDANCE (STAFFID,ATT_DATE,STATUS) values ('SID001',to_date('19-APR-25','DD-MON-RR'),'P       ');
Insert into SYSTEM.ATTENDANCE (STAFFID,ATT_DATE,STATUS) values ('SID001',to_date('20-APR-25','DD-MON-RR'),'P       ');
Insert into SYSTEM.ATTENDANCE (STAFFID,ATT_DATE,STATUS) values ('SID001',to_date('21-APR-25','DD-MON-RR'),'P       ');
Insert into SYSTEM.ATTENDANCE (STAFFID,ATT_DATE,STATUS) values ('SID001',to_date('22-APR-25','DD-MON-RR'),'P       ');
Insert into SYSTEM.ATTENDANCE (STAFFID,ATT_DATE,STATUS) values ('SID001',to_date('23-APR-25','DD-MON-RR'),'A       ');
Insert into SYSTEM.ATTENDANCE (STAFFID,ATT_DATE,STATUS) values ('SID001',to_date('24-APR-25','DD-MON-RR'),'P       ');
Insert into SYSTEM.ATTENDANCE (STAFFID,ATT_DATE,STATUS) values ('SID001',to_date('25-APR-25','DD-MON-RR'),'P       ');
Insert into SYSTEM.ATTENDANCE (STAFFID,ATT_DATE,STATUS) values ('SID001',to_date('26-APR-25','DD-MON-RR'),'P       ');
Insert into SYSTEM.ATTENDANCE (STAFFID,ATT_DATE,STATUS) values ('SID001',to_date('27-APR-25','DD-MON-RR'),'P       ');
Insert into SYSTEM.ATTENDANCE (STAFFID,ATT_DATE,STATUS) values ('SID001',to_date('28-APR-25','DD-MON-RR'),'P       ');
Insert into SYSTEM.ATTENDANCE (STAFFID,ATT_DATE,STATUS) values ('SID001',to_date('29-APR-25','DD-MON-RR'),'P       ');
Insert into SYSTEM.ATTENDANCE (STAFFID,ATT_DATE,STATUS) values ('SID001',to_date('30-APR-25','DD-MON-RR'),'P       ');
REM INSERTING into SYSTEM.BOOKING
SET DEFINE OFF;
Insert into SYSTEM.BOOKING (BOOKINGID,CHECKINDATE,CHECKOUTDATE,BOOKINGDATE,ROOMCATEGORY,GUESTNAME,ROOMID,USERNAME) values ('BK000001',to_date('15-MAY-25','DD-MON-RR'),to_date('23-MAY-25','DD-MON-RR'),to_date('14-MAY-25','DD-MON-RR'),'Suite','eman aijaz','RM006','eman_aijaz');
Insert into SYSTEM.BOOKING (BOOKINGID,CHECKINDATE,CHECKOUTDATE,BOOKINGDATE,ROOMCATEGORY,GUESTNAME,ROOMID,USERNAME) values ('BK000002',to_date('14-MAY-25','DD-MON-RR'),to_date('22-MAY-25','DD-MON-RR'),to_date('14-MAY-25','DD-MON-RR'),'Deluxe','eman aijaz','RM002','eman_aijaz');
Insert into SYSTEM.BOOKING (BOOKINGID,CHECKINDATE,CHECKOUTDATE,BOOKINGDATE,ROOMCATEGORY,GUESTNAME,ROOMID,USERNAME) values ('BK000003',to_date('23-MAY-25','DD-MON-RR'),to_date('31-MAY-25','DD-MON-RR'),to_date('15-MAY-25','DD-MON-RR'),'Suite','hafsa','RM005','eman_aijaz');
Insert into SYSTEM.BOOKING (BOOKINGID,CHECKINDATE,CHECKOUTDATE,BOOKINGDATE,ROOMCATEGORY,GUESTNAME,ROOMID,USERNAME) values ('BK000004',to_date('16-MAY-25','DD-MON-RR'),to_date('23-MAY-25','DD-MON-RR'),to_date('15-MAY-25','DD-MON-RR'),'Single','hjkhkhk','RM001','eman_aijaz');
Insert into SYSTEM.BOOKING (BOOKINGID,CHECKINDATE,CHECKOUTDATE,BOOKINGDATE,ROOMCATEGORY,GUESTNAME,ROOMID,USERNAME) values ('BK000005',to_date('17-MAY-25','DD-MON-RR'),to_date('24-MAY-25','DD-MON-RR'),to_date('16-MAY-25','DD-MON-RR'),'Single','eman aijaz','RM003','eman_aijaz');
Insert into SYSTEM.BOOKING (BOOKINGID,CHECKINDATE,CHECKOUTDATE,BOOKINGDATE,ROOMCATEGORY,GUESTNAME,ROOMID,USERNAME) values ('BK000006',to_date('17-MAY-25','DD-MON-RR'),to_date('24-MAY-25','DD-MON-RR'),to_date('16-MAY-25','DD-MON-RR'),'Suite','eman aijaz','RM006','eman_aijaz');
Insert into SYSTEM.BOOKING (BOOKINGID,CHECKINDATE,CHECKOUTDATE,BOOKINGDATE,ROOMCATEGORY,GUESTNAME,ROOMID,USERNAME) values ('BK000007',to_date('24-MAY-25','DD-MON-RR'),to_date('01-JUN-25','DD-MON-RR'),to_date('17-MAY-25','DD-MON-RR'),'Suite','getrgtyh','RM006','eman_aijaz');
Insert into SYSTEM.BOOKING (BOOKINGID,CHECKINDATE,CHECKOUTDATE,BOOKINGDATE,ROOMCATEGORY,GUESTNAME,ROOMID,USERNAME) values ('BK000008',to_date('18-MAY-25','DD-MON-RR'),to_date('20-MAY-25','DD-MON-RR'),to_date('17-MAY-25','DD-MON-RR'),'Single','eshoo','RM001','eman_aijaz');
REM INSERTING into SYSTEM.INVENTORY
SET DEFINE OFF;
Insert into SYSTEM.INVENTORY (ITEMID,ITEMNAME,ITEMQUANTITY,STATUS) values ('II001','Soap',93,'In Stock');
Insert into SYSTEM.INVENTORY (ITEMID,ITEMNAME,ITEMQUANTITY,STATUS) values ('II002','Towels',45,'Out-of-Stock');
Insert into SYSTEM.INVENTORY (ITEMID,ITEMNAME,ITEMQUANTITY,STATUS) values ('II003','Robes',91,'Out-of-Stock');
Insert into SYSTEM.INVENTORY (ITEMID,ITEMNAME,ITEMQUANTITY,STATUS) values ('II004','Shampoo',97,'In Stock');
Insert into SYSTEM.INVENTORY (ITEMID,ITEMNAME,ITEMQUANTITY,STATUS) values ('II005','Conditioner',15,'Out-of-Stock');
Insert into SYSTEM.INVENTORY (ITEMID,ITEMNAME,ITEMQUANTITY,STATUS) values ('II006','Toothpaste',100,'In Stock');
Insert into SYSTEM.INVENTORY (ITEMID,ITEMNAME,ITEMQUANTITY,STATUS) values ('II007','Toothbrush',77,'Out-of-Stock');
Insert into SYSTEM.INVENTORY (ITEMID,ITEMNAME,ITEMQUANTITY,STATUS) values ('II008','Slippers',26,'Out-of-Stock');
Insert into SYSTEM.INVENTORY (ITEMID,ITEMNAME,ITEMQUANTITY,STATUS) values ('II009','Tissue Box',94,'In Stock');
Insert into SYSTEM.INVENTORY (ITEMID,ITEMNAME,ITEMQUANTITY,STATUS) values ('II010','Bath Mat',5,'Out-of-Stock');
Insert into SYSTEM.INVENTORY (ITEMID,ITEMNAME,ITEMQUANTITY,STATUS) values ('II011','Laundry Bag',63,'Out-of-Stock');
Insert into SYSTEM.INVENTORY (ITEMID,ITEMNAME,ITEMQUANTITY,STATUS) values ('II012','Water Bottle',92,'In Stock');
Insert into SYSTEM.INVENTORY (ITEMID,ITEMNAME,ITEMQUANTITY,STATUS) values ('II013','Pillow Cover',28,'Out-of-Stock');
Insert into SYSTEM.INVENTORY (ITEMID,ITEMNAME,ITEMQUANTITY,STATUS) values ('II014','Blanket',73,'Out-of-Stock');
Insert into SYSTEM.INVENTORY (ITEMID,ITEMNAME,ITEMQUANTITY,STATUS) values ('II015','Room Key Card',99,'In Stock');
Insert into SYSTEM.INVENTORY (ITEMID,ITEMNAME,ITEMQUANTITY,STATUS) values ('II016','Notepad',11,'Out-of-Stock');
Insert into SYSTEM.INVENTORY (ITEMID,ITEMNAME,ITEMQUANTITY,STATUS) values ('II017','Pen',96,'In Stock');
Insert into SYSTEM.INVENTORY (ITEMID,ITEMNAME,ITEMQUANTITY,STATUS) values ('II018','Hangers',0,'Out-of-Stock');
Insert into SYSTEM.INVENTORY (ITEMID,ITEMNAME,ITEMQUANTITY,STATUS) values ('II019','Curtains',88,'Out-of-Stock');
Insert into SYSTEM.INVENTORY (ITEMID,ITEMNAME,ITEMQUANTITY,STATUS) values ('II020','Hair Dryer',100,'In Stock');
REM INSERTING into SYSTEM.FEEDBACK
SET DEFINE OFF;
Insert into SYSTEM.FEEDBACK (FEEDBACKID,FEEDBACKTYPE,DESCRIPTION,STARS,USERID,USERNAME) values ('FBID001','Anonymous','Great hotel experience. Staff was professional and the hotel was very clean.',5,'GID001','eman_aijaz');
Insert into SYSTEM.FEEDBACK (FEEDBACKID,FEEDBACKTYPE,DESCRIPTION,STARS,USERID,USERNAME) values ('FBID002','Non-Anonymous','Room service was a bit slow but overall good stay.',4,'GID002','hafsa_zakir');
Insert into SYSTEM.FEEDBACK (FEEDBACKID,FEEDBACKTYPE,DESCRIPTION,STARS,USERID,USERNAME) values ('FBID003','Anonymous','Loved the rooftop pool and gym. Will visit again!',5,'GID003','hamza_ahmed');
--------------------------------------------------------
--  DDL for Index SYS_C007404
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C007404" ON "SYSTEM"."USERS" ("USERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Index SYS_C007434
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C007434" ON "SYSTEM"."TASK" ("TASKID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Index SYS_C007424
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C007424" ON "SYSTEM"."SUPPLIER" ("SUPPLIERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Index SYS_C007415
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C007415" ON "SYSTEM"."ROOM" ("ROOMID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Index SYS_C007455
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C007455" ON "SYSTEM"."PAYROLL" ("PAYROLL_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Index SYS_C007413
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C007413" ON "SYSTEM"."BOOKING" ("BOOKINGID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Index SYS_C007421
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C007421" ON "SYSTEM"."FEEDBACK" ("FEEDBACKID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."USERS" ADD PRIMARY KEY ("USERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
--------------------------------------------------------
--  Constraints for Table TASK
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."TASK" ADD PRIMARY KEY ("TASKID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
--------------------------------------------------------
--  Constraints for Table SUPPLIER
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."SUPPLIER" ADD PRIMARY KEY ("SUPPLIERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
--------------------------------------------------------
--  Constraints for Table ROOM
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."ROOM" ADD PRIMARY KEY ("ROOMID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
--------------------------------------------------------
--  Constraints for Table REGISTER
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."REGISTER" MODIFY ("PASS" NOT NULL ENABLE)
  ALTER TABLE "SYSTEM"."REGISTER" MODIFY ("EMAIL" NOT NULL ENABLE)
  ALTER TABLE "SYSTEM"."REGISTER" MODIFY ("USERNAME" NOT NULL ENABLE)
--------------------------------------------------------
--  Constraints for Table PAYROLL
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."PAYROLL" ADD PRIMARY KEY ("PAYROLL_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
  ALTER TABLE "SYSTEM"."PAYROLL" ADD CHECK (p_status IN ('Paid', 'Pending')) ENABLE
  ALTER TABLE "SYSTEM"."PAYROLL" MODIFY ("P_STATUS" NOT NULL ENABLE)
  ALTER TABLE "SYSTEM"."PAYROLL" MODIFY ("AMOUNT_P" NOT NULL ENABLE)
  ALTER TABLE "SYSTEM"."PAYROLL" MODIFY ("PAY_MONTH" NOT NULL ENABLE)
  ALTER TABLE "SYSTEM"."PAYROLL" MODIFY ("DP" NOT NULL ENABLE)
  ALTER TABLE "SYSTEM"."PAYROLL" MODIFY ("STAFF_NAME" NOT NULL ENABLE)
  ALTER TABLE "SYSTEM"."PAYROLL" MODIFY ("STAFF_ID" NOT NULL ENABLE)
--------------------------------------------------------
--  Constraints for Table BOOKING
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."BOOKING" ADD PRIMARY KEY ("BOOKINGID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
--------------------------------------------------------
--  Constraints for Table FEEDBACK
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."FEEDBACK" ADD PRIMARY KEY ("FEEDBACKID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
--------------------------------------------------------
--  Ref Constraints for Table FEEDBACK
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."FEEDBACK" ADD FOREIGN KEY ("USERID")
	  REFERENCES "SYSTEM"."USERS" ("USERID") ENABLE
